import { useRef, useState } from "react";
import { Download, File, FileArchive, FileImage, FileText, LoaderCircle, Trash2, UploadCloud } from "lucide-react";
import type { Attachment } from "../services/attachment";

interface Props { attachments: Attachment[]; loading: boolean; uploading: boolean; currentUserId?: string; onUpload: (file: File) => Promise<void>; onDelete: (id: string) => Promise<void>; }
const fileSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.ceil(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
const attachmentUrl = (url: string) => `${import.meta.env.VITE_API_URL ?? "http://localhost:3000"}${url}`;
const iconFor = (type: string) => type.startsWith("image/") ? FileImage : type.includes("pdf") || type.includes("word") || type.includes("text") ? FileText : type.includes("zip") ? FileArchive : File;

export default function TaskAttachments({ attachments, loading, uploading, currentUserId, onUpload, onDelete }: Props) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState("");
  const [deletingId, setDeletingId] = useState("");
  const upload = async () => { if (!file) return; setMessage(""); try { await onUpload(file); setFile(null); if (inputRef.current) inputRef.current.value = ""; setMessage("Attachment uploaded successfully."); } catch (error: unknown) { const response = (error as { response?: { data?: { message?: string | string[] } } }).response; const detail = response?.data?.message; setMessage(Array.isArray(detail) ? detail[0] : detail ?? "Could not upload this file."); } };
  const remove = async (attachment: Attachment) => { if (!window.confirm(`Delete ${attachment.fileName}? This cannot be undone.`)) return; setDeletingId(attachment.id); try { await onDelete(attachment.id); } catch { setMessage("Could not delete this attachment."); } finally { setDeletingId(""); } };

  return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-900">Attachments</h2><p className="mt-1 text-sm text-slate-500">Share useful files with everyone working on this task.</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-sm font-semibold text-violet-700">{attachments.length} file{attachments.length === 1 ? "" : "s"}</span></div>
    <div className="mt-5 rounded-xl border-2 border-dashed border-violet-200 bg-violet-50/50 p-5"><div className="flex flex-wrap items-center gap-4"><span className="rounded-xl bg-violet-600 p-3 text-white"><UploadCloud size={22} /></span><div className="min-w-50 flex-1"><label htmlFor="attachment-file" className="cursor-pointer font-semibold text-violet-700 hover:text-violet-900">Choose a file</label><p className="text-sm text-slate-500">Maximum size 10 MB. Documents, images, archives and more are supported.</p><input ref={inputRef} id="attachment-file" type="file" className="sr-only" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setMessage(""); }} /></div>{file && <div className="rounded-lg bg-white px-3 py-2 text-sm text-slate-700 shadow-sm">{file.name} <span className="text-slate-400">({fileSize(file.size)})</span></div>}<button onClick={upload} disabled={!file || uploading} className="rounded-lg bg-violet-600 px-4 py-2 font-medium text-white hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-50">{uploading ? "Uploading..." : "Upload"}</button></div></div>
    {message && <p className="mt-3 text-sm text-slate-600" role="status">{message}</p>}
    {loading ? <div className="mt-5 flex items-center gap-2 text-sm text-slate-500"><LoaderCircle className="animate-spin" size={18} /> Loading attachments...</div> : attachments.length === 0 ? <div className="mt-5 rounded-xl bg-slate-50 p-7 text-center text-sm text-slate-500">No files yet. Add the first attachment above.</div> : <ul className="mt-5 divide-y divide-slate-100 rounded-xl border border-slate-100">{attachments.map((a) => { const Icon = iconFor(a.mimeType); const own = a.uploaderId === currentUserId; return <li key={a.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div className="flex min-w-0 items-center gap-3"><span className="rounded-xl bg-sky-100 p-2.5 text-sky-600"><Icon size={20} /></span><div className="min-w-0"><a href={attachmentUrl(a.fileUrl)} target="_blank" rel="noreferrer" className="block truncate font-semibold text-slate-800 hover:text-violet-700 hover:underline">{a.fileName}</a><p className="mt-0.5 text-xs text-slate-500">{fileSize(a.fileSize)} · {a.uploader?.name ?? "Unknown user"} · {new Date(a.uploadedAt).toLocaleDateString()}</p></div></div><div className="flex items-center gap-2"><a href={attachmentUrl(a.fileUrl)} target="_blank" rel="noreferrer" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-violet-700" aria-label={`Open ${a.fileName}`}><Download size={18} /></a>{own && <button onClick={() => remove(a)} disabled={deletingId === a.id} className="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600 disabled:opacity-50" aria-label={`Delete ${a.fileName}`}>{deletingId === a.id ? <LoaderCircle className="animate-spin" size={18} /> : <Trash2 size={18} />}</button>}</div></li>; })}</ul>}
  </section>;
}
